name: CI

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches: [ master ]
  pull_request:
    branches: ['**']

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        ruby: ['3.3', '3.2', '3.1', '3.0']
    runs-on: ${{ matrix.os }}
    name: Tests with Ruby ${{ matrix.ruby }}

    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    env:
      BUNDLE_GEMFILE: .ci.gemfile
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
      - name: Install Ruby Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Lint Ruby files
        run: bundle exec rubocop
